version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volume:
      - ./:/app
      -  /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=owais
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
      
    command: npm run dev 

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: owais
      MONGO_INITDB_ROOT_PASSWORD: mypassword
  